src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TXOBJ_StudentBusinessObject.cls
public with sharing class TXOBJ_StudentBusinessObject {
	DAO_StudentDao studentDao;
	
	public TXOBJ_StudentBusinessObject(DAO_StudentDao studentDao) {
		this.studentDao = studentDao;
	}
	
	public TXOBJ_StudentBusinessObject() {
		this(new DAO_StudentDao());
	}
	
	public List<TXOBJ_StudentValueObject> getAllStudents() {
		List<TXOBJ_StudentValueObject> studentValueObjectList = new List<TXOBJ_StudentValueObject>();
		for (Student__c student : this.studentDao.selectAll()) {
			studentValueObjectList.add(new TXOBJ_StudentValueObject(student));
		}
		return studentValueObjectList;
	}
	
	public TXOBJ_StudentValueObject getStudent(Integer enrollmentNumber) {
		return new TXOBJ_StudentValueObject(this.studentDao.selectByEnrollmentNumber(enrollmentNumber));
	}
	
	public void updateStudent(TXOBJ_StudentValueObject studentValueObject) {
		Student__c student = this.studentDao.selectByEnrollmentNumber(studentValueObject.enrollmentNumber);
		student.Name__c = studentValueObject.name;
		this.studentDao.doUpdate(student); 
	}
	
	public void deleteStudent(TXOBJ_StudentValueObject student) {
		this.studentDao.doDelete(student.enrollmentNumber);
	}
	
	
}