src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>EnrollmentNumber__c</fullName>
        <externalId>true</externalId>
        <label>Enrollment Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DAO_DaoPatternDemo.cls
public with sharing class DAO_DaoPatternDemo {
	DAO_StudentDao studentDao;
	public DAO_DaoPatternDemo(DAO_StudentDao studentDao) {
		this.studentDao = studentDao;
	}

	public DAO_DaoPatternDemo() {
		this(new DAO_StudentDao());
	}
	
	private static final Integer ROBERT_ENROLLMENT_NUMBER = 999999991; 
	private static final Integer JOHN_ENROLLMENT_NUMBER = 999999992; 
	
	
    public static void main() {
    	(new DAO_DaoPatternDemo()).demonstrate(); 
    }
    
    private void demonstrate() {
    	// Prepare
    	this.createStudents();
    	 
    	// Demonstrate
    	for (Student__c student : this.studentDao.selectAll()) {
    		System.debug('Student: [Enrollment Number: ' + student.EnrollmentNumber__c + ', Name: ' + student.Name__c + ']');
    	}
    	
    	Student__c student = this.studentDao.selectByEnrollmentNumber(ROBERT_ENROLLMENT_NUMBER);
    	student.name__c = 'Michael';
    	this.studentDao.doUpdate(student);
    	
    	student = this.studentDao.selectByEnrollmentNumber(ROBERT_ENROLLMENT_NUMBER);
    	System.debug('Student: [Enrollment Number: ' + student.EnrollmentNumber__c + ', Name: ' + student.Name__c + ']');
    	
    	// Clean Up 
    	this.deleteStudents();
    }
    
    private void createStudents() {
    	this.studentDao.doInsert(new List<Student__c>{ 
    			new Student__c( Name__c = 'Robert', EnrollmentNumber__c = ROBERT_ENROLLMENT_NUMBER ),
    			new Student__c( Name__c = 'John', EnrollmentNumber__c = JOHN_ENROLLMENT_NUMBER )
    	});
    }

    private void deleteStudents() {
    	this.studentDao.doDelete(this.studentDao.selectByEnrollmentNumber(new Set<Integer>{
    		ROBERT_ENROLLMENT_NUMBER, JOHN_ENROLLMENT_NUMBER
    	}));
    }
}