src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>EnrollmentNumber__c</fullName>
        <externalId>true</externalId>
        <label>Enrollment Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TXOBJ_StudentValueObject.cls
public with sharing class TXOBJ_StudentValueObject {
    public String name;
    public Integer enrollmentNumber;
    
    public TXOBJ_StudentValueObject(String name, Integer enrollmentNumber) {
    	this.name = name;
    	this.enrollmentNumber = enrollmentNumber;
    }
    
    public TXOBJ_StudentValueObject(Student__c student) {
    	this(student.Name__c, (Integer) student.EnrollmentNumber__c);
    }
}